### PR TITLE
Fixed bug with .calc_p_vals util function

### PR DESCRIPTION
**Pull request by ajxa**
The function was referencing the wrong data.table when filtering out missing count values, resulting in a data.table error:

image

### CODE REVIEW

**Comment by nilseling** [comment]
Hmm, which version of `imcRtools` are you using? `dat_baseline` and `dat_stat` should have the same number of rows

**Comment by ajxa** [comment]
Hi Nils, I'm using version 1.3.10

**Comment by nilseling** [comment]
That's already quite an old version. Could you please update to the newest devel version `1.5.2` and see if the error persists?

**Comment by nilseling** [comment]
Could you potentially also share the data that you are working with for me to have a look?

**Comment by nilseling** [comment]
Hi @ajxa 

are there any updates on this? If the issue still occurs in the newest version of the package, could you please send me the data at nils.eling@uzh.ch?

**Comment by nilseling** [comment]
Hi @ajxa 

I have now release a new version of `imcRtools` (1.5.5). Could you please install it via `remotes::install_github("BodenmillerGroup/imcRtools")` and let me know if the issue is fixed?

**Comment by nilseling** [comment]
I'm now closing this due to inactivity

**Pull request closed without merging**
