### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by lassedochreden**
relates to arm64 build errors on BioC

Fixed the error for `countInteractions()` - seems to be related to small floating point errors 

Did **not** fix the error in `test_integration_interactions.R` - did not find a quick fix - potentially related to different NA handling (see screenshot below) - would be great, if @nilseling could have a look. 

Will update NEWS and DESCRIPTION upon approval. 

Screen Shot 2024-10-07 at 17 48 07

### CODE REVIEW

**Comment by nilseling** [comment]
Thanks for looking into it! Could you figure out which p value is correct by comparing the count against the permutations? imcRtools let's you set the return_samples parameter for this.

**Comment by nilseling** [comment]
Ok, in this case I'm 95% sure that the old implementation of the function is generating a wrong p value due to floating point issues. Would be good to double check though

**Comment by lassedochreden** [comment]
Also now fixed `test_integration_interactions.R` - Was related to machine precision issues, which we did not consider when manually calculating the p-values (despite doing so in the function implementation). 

Will merge, if you agree.

**Comment by lassedochreden** [comment]
@SchulzDan - Please push to BioC, when you can.

**Comment by nilseling** [comment]
I noticed that there is this `max(ct_obs)==0` call in `utils.R` when calculating the p values. And since a count of 0 is now not detected as 0 anymore I wondered if this also needs to be replaced.

**Pull request merged**
