### PR TITLE
Read steinbock

### PR DESCRIPTION
**Pull request by nilseling**
Reader function for steinbock output

### CODE REVIEW

**Comment by jwindhager** [comment]
Should be `regionprops`, not `regionprobs` ;-)

**Comment by jwindhager** [comment]
Looks splendid to me otherwise (haven't checked the use of `SelfHits` though). Thanks for the effort!

**Comment by nilseling** [comment]
Aight! It's good to go once the checks pass.

**Comment by nilseling** [comment]
I'll sort this one out tomorrow

**Pull request merged**
